# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('description', models.TextField()),
                ('answer_a', models.CharField(max_length=255)),
                ('answer_b', models.CharField(max_length=255)),
                ('answer_c', models.CharField(max_length=255)),
                ('answer_d', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Category')),
            ],
            options={
                'ordering': ('category', 'question'),
            },
        ),
    ]
